import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import { MyContextProvider } from "@/context/DataContext";
import type { Metadata } from "next";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Al-Almiya Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MyContextProvider>
        <Nav />
        {children}
      </MyContextProvider>
      {<Footer />}
    </>
  );
}
